// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: api/proto/blockchain.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_blockchain_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type WalletCreate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WalletName string `protobuf:"bytes,1,opt,name=walletName,proto3" json:"walletName,omitempty"`
	Balance    int64  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
}

func (x *WalletCreate) Reset() {
	*x = WalletCreate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_blockchain_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WalletCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletCreate) ProtoMessage() {}

func (x *WalletCreate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletCreate.ProtoReflect.Descriptor instead.
func (*WalletCreate) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{1}
}

func (x *WalletCreate) GetWalletName() string {
	if x != nil {
		return x.WalletName
	}
	return ""
}

func (x *WalletCreate) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type SendMoney struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WalletSender    string `protobuf:"bytes,1,opt,name=walletSender,proto3" json:"walletSender,omitempty"`
	WalletRecipient string `protobuf:"bytes,2,opt,name=walletRecipient,proto3" json:"walletRecipient,omitempty"`
	SendMoney       int64  `protobuf:"varint,3,opt,name=sendMoney,proto3" json:"sendMoney,omitempty"`
}

func (x *SendMoney) Reset() {
	*x = SendMoney{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_blockchain_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMoney) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMoney) ProtoMessage() {}

func (x *SendMoney) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMoney.ProtoReflect.Descriptor instead.
func (*SendMoney) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{2}
}

func (x *SendMoney) GetWalletSender() string {
	if x != nil {
		return x.WalletSender
	}
	return ""
}

func (x *SendMoney) GetWalletRecipient() string {
	if x != nil {
		return x.WalletRecipient
	}
	return ""
}

func (x *SendMoney) GetSendMoney() int64 {
	if x != nil {
		return x.SendMoney
	}
	return 0
}

var File_api_proto_blockchain_proto protoreflect.FileDescriptor

var file_api_proto_blockchain_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1d, 0x0a, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x48, 0x0a, 0x0c, 0x57,
	0x61, 0x6c, 0x6c, 0x65, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x77,
	0x61, 0x6c, 0x6c, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x62,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x62, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x77, 0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x6f, 0x6e,
	0x65, 0x79, 0x12, 0x22, 0x0a, 0x0c, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x53, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74,
	0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x0f, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74,
	0x52, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x52, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x32, 0x86,
	0x01, 0x0a, 0x0b, 0x47, 0x72, 0x70, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x21,
	0x0a, 0x09, 0x47, 0x65, 0x74, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x12, 0x08, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x08, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x00, 0x12, 0x29, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x61, 0x6c, 0x6c, 0x65,
	0x74, 0x12, 0x0d, 0x2e, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x1a, 0x08, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x29, 0x0a, 0x0f,
	0x53, 0x65, 0x6e, 0x64, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x12,
	0x0a, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x1a, 0x08, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_blockchain_proto_rawDescOnce sync.Once
	file_api_proto_blockchain_proto_rawDescData = file_api_proto_blockchain_proto_rawDesc
)

func file_api_proto_blockchain_proto_rawDescGZIP() []byte {
	file_api_proto_blockchain_proto_rawDescOnce.Do(func() {
		file_api_proto_blockchain_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_blockchain_proto_rawDescData)
	})
	return file_api_proto_blockchain_proto_rawDescData
}

var file_api_proto_blockchain_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_blockchain_proto_goTypes = []interface{}{
	(*Message)(nil),      // 0: Message
	(*WalletCreate)(nil), // 1: WalletCreate
	(*SendMoney)(nil),    // 2: SendMoney
}
var file_api_proto_blockchain_proto_depIdxs = []int32{
	0, // 0: GrpcService.GetWallet:input_type -> Message
	1, // 1: GrpcService.CreateWallet:input_type -> WalletCreate
	2, // 2: GrpcService.SendMoneyWallet:input_type -> SendMoney
	0, // 3: GrpcService.GetWallet:output_type -> Message
	0, // 4: GrpcService.CreateWallet:output_type -> Message
	0, // 5: GrpcService.SendMoneyWallet:output_type -> Message
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_blockchain_proto_init() }
func file_api_proto_blockchain_proto_init() {
	if File_api_proto_blockchain_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_blockchain_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_blockchain_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WalletCreate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_blockchain_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMoney); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_blockchain_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_blockchain_proto_goTypes,
		DependencyIndexes: file_api_proto_blockchain_proto_depIdxs,
		MessageInfos:      file_api_proto_blockchain_proto_msgTypes,
	}.Build()
	File_api_proto_blockchain_proto = out.File
	file_api_proto_blockchain_proto_rawDesc = nil
	file_api_proto_blockchain_proto_goTypes = nil
	file_api_proto_blockchain_proto_depIdxs = nil
}
